name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: Restoring DotNet packages

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Building code

- task: DotNetCoreCLI@2
  displayName: Running unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: Packing the app

- task: PublishBuildArtifacts@1
  displayName: Publishing artifacts